### ISSUE TITLE
App crashes when clicking on song from queue, and top element of queue not clickable

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#108]
**Describe the bug**
The app crashes when any song is clicked from the queue. Also the top element of the playing queue is not clickable, you cannot drag it around and rearrange it like the rest of the queue.

**To Reproduce**
1. Go to playing queue
2. Try to drag top song from handle. It doesn't work.
3. Click on any other song. App crashes.

**Comment by Benji377** [comment]
Could this be related to issue #98?

**Comment by squivix** [comment]
> Could this be related to issue #98?

Actually the crashing was caused by the fix of issue #89. It's the same exception as the one from issue #98 (visualizer used again before being released) but not for the same reason and not from the same fragment.

As for the dragging thing, that was always there. I just never noticed it.

**Comment by Benji377** [comment]
I use the app daily and never noticed it either lmao. To be fair, I am just too lazy to rearrange songs, so most of the time I just click on the shuffle button a couple of times until I get a queue I am kind of ok with it and let it play
