### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [Benji377/SocyMusic#12]
Currently, your latest release still identifies as `versionCode: 1` despite being not the first release (Android uses `versionCode` to tell versions apart; only higher values are accepted as updates). Further, it claims to be version 1.0 while it is rather 0.2-beta.

May I suggest to [adjust the values](https://github.com/Benji377/SocyMusic/blob/main/app/build.gradle#L13) accordingly before tagging a new release? For the current one, that could look like

```gradle
   versionCode 2
   versionName "0.2-beta"
```

It's a good practice to keep `versionName` in sync with the tag name as well – with a prepended `v` as you already do, hence I adjusted my suggestion to that.

Thanks in advance!

**Comment by Benji377** [comment]
Thank you very much, I completely forgot to do that. I'm gonna fix it immediately

**Comment by Benji377** [comment]
versionCode and versionName have been updated. I will need to remind myself to change it every time we release a new version.
Thank you again for pointing it out.

**Comment by IzzySoft** [comment]
Thanks a lot! Will you also replace the APK at the latest tag (no need to fix the older one)? Else it might look a bit strange when an update has a "lower versionName" :wink:

**Comment by Benji377** [comment]
Done, now everything should be correct

**Comment by IzzySoft** [comment]
Thanks a lot – and yes, it is! Will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.example.musicplayer) with the next regular sync tomorrow (usually around 7:45pm CEST/UTC+2), updates will be fetched within 24h of your attaching an APK to a new tag. Will add it to my [corresponding app list](https://android.izzysoft.de/applists/category/named/multimedia_music_jukeboxen) as well after the sync, so hopefully that will raise awareness and bring the one or other contributor to you as well :smiley:
