### ISSUE TITLE
Scrolling PlayerFragment sheet vertically is awkward

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#125]
**Describe the bug**
Due to the newly added viewpager in PlayerFragment, the bottom sheet that the whole fragment is on is not scrolling very well. If you start scrolling vertically where the ViewPager is, it doesn't register. ViewPagers  and BottomSheets don't work well together, so it seems this is a common problem.

**To Reproduce**
1. Open app
2. Click on song to open PlayerFragment
3. Try to duck down the bottomsheet that pops up by dragging from the center (where the album art and song title go)
4. Notice scrolling doesn't work until you reach the bottom where the ViewPager ends

**Comment by Benji377** [comment]
If you try to drag it down from anywhere else than where the somg thumbnail or title is it works just fine. I think it has something do to with the new viewpager that has been added recently. It probably only accepts left and right swipes so you need to add a listener for down swipes too.

**Comment by Benji377** [comment]
Looking at [this tutorial](https://www.geeksforgeeks.org/viewpager2-in-android-with-example/) it seems like a Viewpager2 can get top to bottom swipes. So then there was [this guy](https://stackoverflow.com/questions/62200351/nested-viewpager2?rq=1) which had a similar problem I think. Another similar problem could be [this one](https://stackoverflow.com/questions/56647971/how-to-disable-swiping-in-specific-direction-in-viewpager2).
It just seems like the Viewpager2 only accepts one direction, either horizontally or vertically, not both at the same time.

Another solution we might try is to always prioritize top to bottom swipes to Viewpager2 swipes. We would need to check if the user is swiping downwards and if he is, lock the Viewpager and make him move downwards, else unlock the viewpager2.

**Comment by Benji377** [comment]
Actually, check this out: 
1. Edit the Viewpager2 code in fragment_player.xml to this:
```
        <androidx.viewpager2.widget.ViewPager2
            android:id="@+id/viewpager_player_song"
            android:layout_width="match_parent"
            android:layout_height="325dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            android:layout_marginTop="75dp"
            android:orientation="vertical"/>
```
2. Start the emulator or whatever and go to the first song. Click on it
3. Now that the Playerfragment showed up, try to swipe up and down and it will change the songs as normal
4. BUT if you are on the first song and try to swipe any further, the Viewpager2 does exactly what we want it to do:
5. The whole playerfragment gets dragged along because the Viwpager2 can't go any further.

**Comment by squivix** [comment]
I'm pretty sure the solution isn't to vga the scrolling direction of the viewpager2 but to somehow make it pass vertical scrolling to its container.

**Comment by Benji377** [comment]
But we still need something like a swipe listener to check for vertical swipes, right?

**Comment by Benji377** [comment]
This might be a solution? [Stackoverflow](https://stackoverflow.com/a/35436859)

**Comment by squivix** [comment]
> This might be a solution? [Stackoverflow](https://stackoverflow.com/a/35436859) Or maybe [this one](https://stackoverflow.com/questions/60640368/vertical-viewpager2-with-recyclerview-scrolling-issue) is probably a better one
The first one is using ViewPager instead of ViewPager2. The second one I already tried.

**Comment by squivix** [comment]
Ok I asked around the discord servers and someone helped me out with it. His solution was to access the RecyclerView inside the ViewPager2 and disable its nested scrolling with a Kotlin extension function:

```
    fun ViewPager2.disableNestedScrolling() {
        (getChildAt(0) as? RecyclerView)?.apply {
            isNestedScrollingEnabled = false
            overScrollMode = View.OVER_SCROLL_NEVER
        }
    }
```

Unfortunately it meant I had to convert the CustomViewPager2 class to Kotlin, which I don't speak. Still it's worth it. Although you'll have to download a Kotlin plugin to compile. I wanna learn Kotlin some day anyway.

**Comment by Benji377** [comment]
Damn this bug was hard to get rid off

**Comment by squivix** [comment]
Good news! I managed to get it to work in Java! So forget the last update.

**Comment by Benji377** [comment]
Great! Oh and by the way, @squivix look at [this](https://www.reddit.com/r/androidapps/comments/ph1iue/what_are_some_features_you_would_ike_to_see_in_an/?utm_source=share&utm_medium=web2x&context=3). I asked Reddit what they would like to see in our music player and I never expected that many replies. I think this project will never end hahah. I will also try to recruit some more devs and designers to help us.
