### ISSUE TITLE
Enabling the SD card in settings crashes SocyMusic

### ISSUE THREAD

**Issue by Piscean** [Benji377/SocyMusic#187]
My music all lives on the SD card.  When I go to SocyMusic Settings and enable searching the SD card for music, the app hangs, then crashes.

I have almost 6,000 songs.  Everything is organized in directories:
  SD
    Music
       Artist 1
          Album 1
            Song 1
            Song 2
          Album 2

I assume that's how everyone stores their music, but maybe not.

**Comment by squivix** [comment]
Which version of the app are you using? The latest release (1.2.0)?

It would be really helpful to see the crash log, but I understand that's hard to set up.

**Comment by Piscean** [comment]
I'm on v1.2.0.

I've never gotten the crash dump stuff to work.  I get as far as connecting via USB and then ADB says there are 2 devices connected.  If I unplug, then there are no devices.  So my phone shows up as 2 devices and I haven't spent the time to figure out how to distinguish which of the 2 is correct and move forward.  I'll try to work on it again if I have time this weekend.

**Comment by Benji377** [comment]
Could you please try to use the [latest release](https://github.com/Benji377/SocyMusic/releases/tag/v1.2.1-beta) and tell us if your bug gets fixed?
The app now saves logs on your phone and even if you can deactivate the option in the settings, it should be active by default. Therefore if the app still crashes could you please go to the following path in your phone and send us the .txt files located there?
The path: `Android/data/com.musicplayer.socymusic/logs`

**Comment by Piscean** [comment]
This version finds the music on the SD card.  Looks like the issue is fixed.

**Comment by Benji377** [comment]
That's great news, thanks for reporting the issue!
