### ISSUE TITLE
Notification not showing the right information

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#28]
Notification is finally successfully displayed when the app starts, but there are some enhancements that need to be made:
- Only show Notification while the song is playing
- Make Notification indestructible while the song is playing
- Automatically stop showing the Notification when song stops or app is stopped
- Show song name and maybe buttons on the Notification
- Update Notification if another song gets played

**Comment by squivix** [comment]
I've never done this before but from the googling I've done, I think we need to make a MediaSessionService. So it's a bit more complicated than we've made it. Here's a few links:

https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice#java

https://stackoverflow.com/questions/63501425/java-android-media-player-notification

**Comment by Benji377** [comment]
Tell me if I can help you in any way

**Comment by Benji377** [comment]
@squivix you are insane. It took me weeks to figure out how to create a simple, not even completely working Notification and you just did it in two days???

Thank you very much for your huge help in creating this project, I tested it and it works wonderfully. Now we can work on the menu and close this issue. I will publish a release later today.

**Comment by squivix** [comment]
> @squivix you are insane. It took me weeks to figure out how to create a simple, not even completely working Notification and you just did it in two days???

That's very nice of you :D
I'm a little more experienced with android and Java than you seem to be but trust me, I'm still a beginner. I didn't know how to do this either. I did a lot of googling and followed a few youtube tutorials.

**Comment by Benji377** [comment]
I started learning Java this year and I thought it would be cool to build a "simple" music player for my phone. My main language is Python.
