### ISSUE TITLE
Typos fix

### ISSUE THREAD

**Issue by rustom** [Benji377/SocyMusic#3]
There are a couple typos/missing words in your repo description and README. Quick fix so people know what they're looking at!

**Comment by Benji377** [comment]
Hey rustom, English is not my native language, and I couldn't find any typos in the description or readme file. Could you please fix them yourself, or maybe tell me where the typos are? Your help would be really appreciated.

**Comment by alimustafashah** [comment]
There are no typos in the readme file. On the other hand, there are several grammatical mistakes : )
