### ISSUE TITLE
About fragment only showing in Player fragment

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#43]
If you click on "Credit" in the dropdown menu while in the MainActivity (Where all songs are listed) nothing happens, but if you click on it while being on the Playerfragment it overlaps the existing fragment and you can see it. 

If you try to do it again it crashes the app. It also seems like the Aboutfragment completely replaces the Playerfragment since even if you click on the menu at the bottom of the screen it will reopen the About instead of the Playerfragment.

**Comment by squivix** [comment]
I think we should hide the action bar buttons while the PlayerFragment is on screen.
