### ISSUE TITLE
PlayerFragment not responsive

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#45]
I noticed that on my friend's phone the Song time numbers weren't displayed correctly. They were squeezed into a tiny space to make room for the seek bar.
Right now the PlayerFragment is a Linearlayout, but maybe it would be better to have it in a ConstraintLayout for better responsiveness and supportiveness on more phones.

**Comment by squivix** [comment]
I noticed this on my phone too actually. Let me know if you can fix it.

**Comment by Benji377** [comment]
Working on it

**Comment by Benji377** [comment]
This is my progress so far. I'm gonna test it now and hope it works. If yes I will create a pull request later

![image](https://user-images.githubusercontent.com/50681275/121420132-035d5a80-c96d-11eb-888a-bd7ac1b5d805.png)

**Comment by Benji377** [comment]
Well, it looks like it's working, but ist not being shown completely because of some weird navbar issue. @squivix I think this is something you might be able to fix. Creating a pull request now

**Comment by Benji377** [comment]
The problem is that when you click on a song and the Fragment should appear, it actually only appears up to a certain point, which is kinda strange. It almost looks like the size of the fragment isn't big enough

**Comment by Benji377** [comment]
Ok, I figured it out myself. I just had to tweak the Framelayout a little bit. Hope it works now responsive.
