### ISSUE TITLE
Strange incompatibility issue with the Popup

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#56]
After coding the popup window, adding a style to it, and testing it on the Android studio emulator everything was looking good. But then I decided to do one last test on my phone and it crashed the app.

This is the error I get:
`?attr/colorAccent' is not set.`

I think it might just be a color missing somewhere. Refer to this StackOverflow answer: https://stackoverflow.com/questions/35813050/error-no-resource-found-that-matches-the-given-name-attr-coloraccent-in-ecli

**Comment by squivix** [comment]
I can't test this with my device or emulator because for some reason I don't have the class AboutPage. Are you adding it to git?

**Comment by Benji377** [comment]
Wait, what? I thought I added it already. Hm... that's even stranger.

**Comment by Benji377** [comment]
Ok, actually there is no AboutPage class. I imported them from Github. I also added an implementation to the build.gradle file.

Refer here:
- https://blog.fossasia.org/creating-an-awesome-about-us-page-for-the-open-event-organizer-android-app/
-  https://github.com/medyo/android-about-page

And these are the imports:
```
import mehdi.sakout.aboutpage.AboutPage;
import mehdi.sakout.aboutpage.Element;
```

**Comment by Benji377** [comment]
This should hopefully fix the issue. Tell me if you still have an issue with this and I will reopen it. @squivix

**Comment by squivix** [comment]
I just resynced my build.gradle file and it works.
