### ISSUE TITLE
Controlling the app with Bluetooth devices

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#65]
Some people use the player in the app directly, some are lazy and control their music using the notification and some, like me, are even lazier and like to control their music player using their Bluetooth headphones. Especially while going around it can be a very helpful feature.

Now, thing is, I haven't done any research yet and I have no idea if that's even possible with our app, but it would be a really cool addition.

**Comment by squivix** [comment]
They call them media buttons and I came across this while I was working on the notification. I think it is possible but we'd need to edit the media service class a bit. I would work on this but I'm currently busy with something else. I'll pick it up in a few days.


If you wanna implement it yourself check out: 
https://developer.android.com/guide/topics/media-apps/mediabuttons

**Comment by Benji377** [comment]
I will check it out but don't worry, there is no stress. When I started this project I had in mind to finish it in like two years and I had no idea I would find someone interested in collaborating and that it would go so fast. I haven't done any serious collaboration before either and this is one of my biggest projects so far. The amount of progress that has been done here is incredible. 

So no worries, I will leave you to it.

**Comment by Benji377** [comment]
Also, refer to #68
