### ISSUE TITLE
PlayerFragment has random behavior

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#76]
**Describe the bug**
When clicking on the playerfragment anywhere where it is not intended that someone clicks it does some strange unpredictable things.
**To Reproduce**
1. Open the app
2. Click on any song in the list
3. Click on the thumbnail of the song for example
4. Notice how even the visualizer disappears

**Expected behavior**
Nothing should happen

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s9+
 - OS: Android 10
 - Browser: None
 - Version: 1.1.2-beta

**Additional context**
I noticed it because I miss clicked a button and suddenly the visualizer disappeared, clicking on a button fixed it again. It also seemed like completely random behavior to me.

**Comment by squivix** [comment]
I noticed this too. Sometimes it skips a song or does something unpredictable. Hard to debug this sort of thing...

**Comment by Benji377** [comment]
A way to debig this might be to use Logcat and see exactly what gets triggered and why. We could add Log.e at onclick listeners and see which click gets triggered. At least that's how I debug tjose things. Maybe one buttons hitbox just has the size of the whole fragment or something.

**Comment by squivix** [comment]
Ok I found out what's going on. The ListView in the main activity is still clickable through the sides of the player fragment.  Fixed by making the player fragment container absorb clicks. Check latest commit in pull request #79

**Comment by Benji377** [comment]
Great job!
