### ISSUE TITLE
We should have a setting for media library path/paths

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#80]
**Is your feature request related to a problem? Please describe.**
Yes. One of the biggest things that annoyed me with the app is that it shows me ALL mp3 and wav files on my device, most of which are not songs. I want it to stop showing me podcasts, voice recordings, ads and other media files I don't even know about from my device. 

**Describe the solution you'd like**
I want there to be a setting that let's me configure where the app looks for songs. I added a blank button in my latest commit (pull request #79) but I'm conflicted on how this should work exactly. There are three ways to go about this that I can think of:

1- Media folders: 
Let the user select which directories on their device the app should look for songs on.  To implement this we'd probably need to use a [directory picker](https://android-arsenal.com/tag/35) or make one on our own. 
2- Blacklist:
Let the user select which directories not to include in the search, a so called blacklist. It'd probably work the same way as 1.
3- Root folder:
Let the user select a single root directory to look for music on. All songs within it will be included, everything else won't be. Here we may not need to use a directory chooser. We could use an intent with ACTION_OPEN_DOCUMENT_TREE then parse its path somehow. I tried to get this to work without parsing its path and it's not possible. It returns a "tree path" which is not a real path you can directly get a File object from. We'd have to use a library to convert that into a real path somehow, and I'm not sure it's worth it...

So I think option 1 is the best to go with. Option 3 is a little restrictive  and option 2 might be cumbersome for a user with lots of non-music media files. I want to try to implement option 1 without a library (so we can have more control over how it looks and acts) but I want to hear from you first. What do you think?

**Comment by Benji377** [comment]
Yeah, you are right. There is just one problem that I also faced with the playlist feature and it is the following: saving the state even when the app gets closed. Right now, if you exit the app and enter again, all progress is lost, nothing gets saved. This means that a user would need to select the folders every time the app gets opened. Else we could maybe give him a list of all directories the app could find/access in a dropdown like menu and he can add more to it using a + button.
Wait, I'm gonna try to draw it:
![Drawing-6 sketchpad](https://user-images.githubusercontent.com/50681275/124382620-9e292a80-dcc8-11eb-8523-ddd968439ee0.png)

This might be a solution, but it creates another problem: People with a lot of folders will have a very long list of dropdown menus.
Tell me what you think

**Comment by squivix** [comment]
The user would not need to select a path every time. Settings are saved and handled by the PreferencesManager class so it's all good there. The user would only need to select a few base directories, any sub-directories inside of them would be included. So I don't think there would be a problem with very long drop-down menus. I will start working on this issue tomorrow. Will see what I can do.

**Comment by Benji377** [comment]
I'm gonna test it with my SD-card which already caused some problems before. If it works this issue can be closed

**Comment by Benji377** [comment]
It works. I need to admit I'm impressed by how good you are @squivix and how bad I am lmao

**Comment by squivix** [comment]
> It works. I need to admit I'm impressed by how good you are @squivix and how bad I am lmao 

Thank you :D

I wouldn't be too impressed though. I used an external library ([this one](https://github.com/hendrawd/StorageUtil)) to find the path to the external storage root because android is such a mess that even something as simple as where the root storage directory is varies wildly by manufacturer.

I also ran into all sorts of problems with permissions and scoped storage.

FYI android is gradually reducing access of apps to the whole storage system even with READ_EXTERNAL_STORAGE permissions. They're switching to what they call scoped storage where the app just launches an intent and the system asks the user for permissions for every specific file. I tried to use the API but it was even more of headache than writing my own directory browser. Point is: in a future update the code may no longer work because Google may decide to pull the plug on legacy storage.

**Comment by Benji377** [comment]
Oh yeah I feel you. When I tried to add support for my SD card I found a lot of problems too. The only solution I came up with was to put the songs in a specific app accessible directory only. But then the songs would disappear on uninstallation.

Because of the future Android problem... Well, I don't know. We could stop updating the SDK version in the build file to avoid issue at first, but then the app could become incompatible with certain versions and that's kinda bad.

**Comment by squivix** [comment]
We will definitely have to embrace it and switch to the MediaStore API for loading songs. As for picking directories, I doubt google will completely remove read access as it will break a lot of apps that definitely need it (like file managers). We will see what happens then I suppose. For now it works (even on the latest android: API level 30) and I'm happy with that :D
