### ISSUE TITLE
App stops playing song when exiting

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#90]
**Describe the bug**
When a song is playing and you exit the app by pressing the home button, everything is fine and the song keeps playing in the background while the notification keeps showing. But if instead of pressing the home button you press the back button, the song stops playing and the notification disappears.

**To Reproduce**
1. Open the app
2. Pick a song from the list
3. Press back once to return to the list
4. Press back again to exit from the app
5. The notification disappears and the song stops playing

**Expected behavior**
the notification should continue to be visible and the song should continue playing.

**Screenshots**
/

**Desktop (please complete the following information):**
/

**Smartphone (please complete the following information):**
 - Device: Samsung s9+
 - OS: Android 10
 - Browser: /
 - Version: latest source code

**Additional context**
/

**Comment by squivix** [comment]
I thought this was working as intended.

So you want the back button to do the same thing as the home button?

**Comment by Benji377** [comment]
Hahaha I was unsure if it was intended or not. But no you are true, let's label it a feature.
It does make sense to have two separate buttons do two separate things. Should have thought better before opening an issue.
