### ISSUE TITLE
Adding the theme changing settings

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#95]
We actually only have one color right now. If you take a look at the themes.xml file or the colors.xml files, there is only one color which is something like red (code: #FF362E). Other colors we have are white and black. This means that if we set a variable there, we could actually set the color code programmatically and therefore change the appearance of the app.
BUT before anyone does anything about it, I would like to talk about something. I will do it in a discussion and link it here once it's published. I don't think it's an issue and therefore doesn't belong here.
The discussion: #96

**Comment by Benji377** [comment]
This is in development. Still need to find a way to make it look cool. Gradients arent good enough.

**Comment by Benji377** [comment]
Here is a [Stackoverflow post about it](https://stackoverflow.com/questions/4381033/multi-gradient-shapes). @squivix is this something you might like? You have better taste than me hahah.

**Comment by squivix** [comment]
I don't really know. I'd need to see it in action I guess.


 We could make the background depend on the album art(when we add that) and black if there is no album art. Or we could keep the old background but give it a different tint depending on color. That would be cool if we got it to work.

In any case, it's not that important. The gradient doesn't look that bad and black looks pretty good too. I'd leave the small touches for later.

**Comment by Benji377** [comment]
If you go into the background.xml you can see that there are three colors. You can play around with them if you want. There is also specified what type of gradient it is and the angle.
I searched up a lot of libraries but none seem to offer what we would like to have. I also asked on Stackoverflow but my answer got taken down because it apparently didn't have anything to do with coding.
The thing is: The user can choose whatever background color he/she wants. If he/she wants to have a poop brown mixed with a bright yellow, I am not going to stop him/her, I'm just going to judge silently lmao

**Comment by Benji377** [comment]
Ok actually I have a Plan B which takes away a little bit of customization from the user, but might make the app a little bit more cool-looking.  Did you know that one of the contributors here is a great designer which also made the icon of the app? Yep, @SilviaJack28 could make the background too, maybe in a couple of different colors and the user could pick which one he/she wants. I'm gonna talk to her and see if she is ok with this.

**Comment by Benji377** [comment]
Hey, @squivix I think @SilviaJack28 did a great job! Here are the results, let me know what you think about it:

![photo_2021-07-22_21-24-21](https://user-images.githubusercontent.com/50681275/126697893-a48f68b3-86c7-4441-ba8d-76896c4a6b93.jpg)
![photo_2021-07-22_21-24-23](https://user-images.githubusercontent.com/50681275/126697899-d86ef5e3-b923-4a5e-a0b7-aef890fb78c4.jpg)
![photo_2021-07-22_21-24-25](https://user-images.githubusercontent.com/50681275/126697902-03d01ec3-aa69-4bff-b691-7ebd4368c567.jpg)
![photo_2021-07-22_21-24-27](https://user-images.githubusercontent.com/50681275/126697904-ac866be6-f49f-4809-82d4-21a92b21eadb.jpg)
![photo_2021-07-22_21-24-29](https://user-images.githubusercontent.com/50681275/126697905-597fd738-7210-4cb2-9444-0f7c86ab5b44.jpg)

And for comparison, here is the old one:
![old_player_background](https://user-images.githubusercontent.com/50681275/126697964-434147e3-818b-438d-bc71-860aeedd65fb.jpg)

**Comment by squivix** [comment]
Looks great! Would love to see it in action though. Can you get a screenshot of PlayerFragment with the new background?

**Comment by Benji377** [comment]
Well uhm... I just found out something really strange lol:
![image](https://user-images.githubusercontent.com/50681275/126702179-2100250a-1143-4db1-bd97-b67bcd9191e3.png)

**Comment by Benji377** [comment]
Ok, never mind, I know what that black box is. It's basically the area where you can swipe to get to the next song. Lets see if I can it to become transparent.

**Comment by Benji377** [comment]
Here we go:

![image](https://user-images.githubusercontent.com/50681275/126703728-90dac7eb-943f-4778-8141-a15c1ba84f40.png)

**Comment by squivix** [comment]
Looks good to me.

**Comment by Benji377** [comment]
Added the backgrounds in pull-request #126 and I also tried to make the colors change, but the problem is that colors are final values and once the app is compiled, the values can't be changed.
I tried another approach where I just change the whole theme, but it seems like you need to restart the Activity to do so and because it gets called from a Fragment it just starts the Activity over and over again.
Ideally, it would be much better to have this set from the settings tab to avoid loops.

**Comment by Benji377** [comment]
This has now been added. Now it's all about testing and fixing some nasty bugs.
