### ISSUE TITLE
Shuffle and queue buttons mess up the song playing

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#98]
**Describe the bug**
Pressing the shuffle button and show queue button a few times seems to make the app show the wrong song playing.

**To Reproduce**
1. Click on a song to play
2. Press the shuffle button
3. Press the queue button
4. Repeat 2 and 3 until title shows wrong song

**Expected behavior**
Shuffling the queue should not affect the song playing, only the rest of the queue.

**Comment by Benji377** [comment]
Hm... yeah I saw. But if you look at the code to generate the random queue, the first song of the queue is picked from the currently playing song and is added immediately and therefore skipped.  If you click on the button again, the queue gets reset.

**Comment by Benji377** [comment]
Ok nope. This is not solved. I managed to make the app crash now. Working on it

**Comment by squivix** [comment]
Ok should be fixed now. Reverting to the original queue means having to keep track of the original queue all the time.

**Comment by Benji377** [comment]
Strangely it was working on the emulator, but as soon as I switched to my phone it broke. But yeah I realized the issue almost at the same time as you hahah.

**Comment by Benji377** [comment]
Further testing is required xD

**Comment by squivix** [comment]
> Further testing is required xD

Always :P

**Comment by Benji377** [comment]
And I found another issue hahhah. If you try this while using the first song in queue, everything is fine. But as soon as you go to the next song and try it there it changes the title again.
This might get fixed by keeping track of what sog is currently playing and not changing it.

**Comment by squivix** [comment]
Ok latest PR sets the playing index to 0 when shuffling and resets it back to what it was when un-shuffling.

**Comment by Benji377** [comment]
And let's test it again and pray. Because I am tired and want to sleep xD

**Comment by Benji377** [comment]
Guess who found another problem with it? Yep...me. If you press the next button and then press the previous button it doesn't actually return to the previous song as it should, but actually just picks a random song. Then if you click on the shuffle button again and look at the queue the title gets reset.

**Comment by squivix** [comment]
Wow this is a persistent bug, or maybe I'm just not very good at testing XD

I hope this one fixes it but if not we'll leave it for tomorrow

**Comment by Benji377** [comment]
Tested and it works now
